version: "3.8"

services:
  frontend:
    build:
      context: ./Vite
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build:
      context: ./server
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/Invites
    ports:
      - "5000:5000"
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Invites
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot # Монтируем директорию с webroot для ACME challenge
      - ./certbot/conf:/etc/letsencrypt # Монтируем сертификаты в контейнер Nginx
    ports:
      - "80:80"
      - "443:443" # Добавлен порт 443 для HTTPS
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot # Монтируем для ACME challenge
      - ./certbot/conf:/etc/letsencrypt # Монтируем для сохранения сертификатов
    networks:
      - app-network
    depends_on:
      - nginx

networks:
  app-network:

volumes:
  postgres_data:
